(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},f=e(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={c:!0},m={};try{m.__proto__=l;k=m.c;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=h,p=function(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(n)n(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c]};var q=function(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"lefttoright"};var r=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},t=function(a){if(r(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&r(a))return a;return null};var u=function(){var a=HTMLElement.call(this)||this;a.a=null;a.frameWidth=0;a.frameHeight=0;return a};p(u,HTMLElement);u.prototype.connectedCallback=function(){var a=this;setTimeout(function(){if(!a.gwdIsLoaded()){var b=t(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},0)};
u.prototype.gwdLoad=function(){var a=this.parentElement.querySelector("canvas");a&&(this.a=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};u.prototype.gwdIsLoaded=function(){return!!this.a};u.prototype.renderAnimation=function(){};var v=function(a,b,c,g){a.a.drawImage(b,c,g,a.frameWidth,a.frameHeight)};
u.prototype.getSupportedSwipeDirection=function(){if("undefined"==typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};u.prototype.setDirection=function(){};u.prototype.resetDirection=function(){};var w=["direction"],x=function(){return u.call(this)||this};p(x,u);x.prototype.connectedCallback=function(){this.b=q(this);u.prototype.connectedCallback.call(this)};x.prototype.attributeChangedCallback=function(a){switch(a){case "direction":this.b=q(this)}};x.prototype.setDirection=function(a){this.b=a};x.prototype.resetDirection=function(){this.b=q(this)};
x.prototype.renderAnimation=function(a,b,c){this.a.save();this.a.clearRect(0,0,this.frameWidth,this.frameHeight);switch(this.b){case "righttoleft":v(this,b,(1-c)*this.frameWidth,0);v(this,a,-c*this.frameWidth,0);break;case "toptobottom":v(this,b,0,(c-1)*this.frameHeight);v(this,a,0,c*this.frameHeight);break;case "bottomtotop":v(this,b,0,(1-c)*this.frameHeight);v(this,a,0,-c*this.frameHeight);break;default:v(this,b,(c-1)*this.frameWidth,0),v(this,a,c*this.frameWidth,0)}this.a.restore()};
f.Object.defineProperties(x,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return w}}});customElements.define("gwd-push",x);}).call(this);
